### ISSUE TITLE
Code does not always detect blocks correctly. Unsure how to fix

### ISSUE THREAD

**Issue by Code4SAFrankie** [artkulak/crossword-data-extraction#1]
I tried with the image below, but it does not detect the blocks correctly for the first two and last two columns. I think the images confuse it. Not sure if the code can be adjusted to work with these kind of images. No clue how to do that myself.

Thanks for the awesome code. Just what I was looking for and was unable to do myself.

![deskew2](https://user-images.githubusercontent.com/6196390/113930804-0a8fad00-97f2-11eb-94af-ca0bb910872c.png)

**Comment by Code4SAFrankie** [comment]
Also fails on this one without images.
![deskew3](https://user-images.githubusercontent.com/6196390/113933736-3ceed980-97f5-11eb-81d4-197f406a8848.png)

**Comment by Code4SAFrankie** [comment]
Tried to do

`cv2.fastNlMeansDenoising(img, img, 30, 7, 21)`

on the image which previously helped with `tesseract` detecting the characters during ocr, but this caused:

```
Traceback (most recent call last):
  File "extractJson.py", line 341, in <module>
    lines, (image, mask) = getLines(img, filter=True)
  File "extractJson.py", line 66, in getLines
    if not lines.any():
AttributeError: 'NoneType' object has no attribute 'any'
```
